/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libreria_ryr;

import ingreso_datos.Agregar_categoria;
import ingreso_datos.Agregar_empleados;
import ingreso_datos.Agregar_proveedor;
import ingreso_datos.Datos_cliente;
import ingreso_datos.Ingresar_productos;
import ingreso_datos.frmListar_cat;
import ingreso_datos.frmListar_cli;
import ingreso_datos.frmListar_emp;
import ingreso_datos.frmListar_prov;
import java.awt.Color;
import java.awt.ComponentOrientation;
import static java.awt.SystemColor.menu;
import ventas.Nventa;

/**
 *
 * @author Miguel Benavides
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
        this.setExtendedState(MenuAdmin.MAXIMIZED_BOTH);
        
        menuInicio.setBackground(new java.awt.Color(106,199,237));
        menuVenta.setBackground(new java.awt.Color(106,199,237));
        menuProv.setBackground(new java.awt.Color(106,199,237));
        menuProd.setBackground(new java.awt.Color(106,199,237));
        menuCat.setBackground(new java.awt.Color(106,199,237));
        menuEmp.setBackground(new java.awt.Color(106,199,237));
        menuCliente.setBackground(new java.awt.Color(106,199,237));
        //MenuAdm.setBackground(Color.yellow);
        menuInicio.setOpaque(true);
        menuVenta.setOpaque(true);
        menuProv.setOpaque(true);
        menuProd.setOpaque(true);
        menuCat.setOpaque(true);
        menuEmp.setOpaque(true);
        menuCliente.setOpaque(true);
        //MenuAdm.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem13 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        MenuAdm = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuVenta = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuProv = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuProd = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuCat = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        menuEmp = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        jMenuItem13.setText("jMenuItem13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1187, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        MenuAdm.setAlignmentX(1.0F);
        MenuAdm.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N

        menuInicio.setBackground(new java.awt.Color(204, 204, 255));
        menuInicio.setBorder(null);
        menuInicio.setForeground(new java.awt.Color(255, 255, 255));
        menuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreria_ryr/home.png"))); // NOI18N
        menuInicio.setText("Inicio");
        menuInicio.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        menuInicio.setVerifyInputWhenFocusTarget(false);

        jMenuItem1.setText("Cerrar Sesion");
        menuInicio.add(jMenuItem1);

        MenuAdm.add(menuInicio);

        menuVenta.setForeground(new java.awt.Color(255, 255, 255));
        menuVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreria_ryr/shopping-cart.png"))); // NOI18N
        menuVenta.setText("Venta");
        menuVenta.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N

        jMenuItem2.setText("Generer Venta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuVenta.add(jMenuItem2);

        MenuAdm.add(menuVenta);

        menuProv.setForeground(new java.awt.Color(255, 255, 255));
        menuProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreria_ryr/truck.png"))); // NOI18N
        menuProv.setText("Proveedor");
        menuProv.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N

        jMenuItem3.setText("Agregar Proveedor");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuProv.add(jMenuItem3);

        jMenuItem4.setText("Listar Proveedores");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuProv.add(jMenuItem4);

        MenuAdm.add(menuProv);

        menuProd.setForeground(new java.awt.Color(255, 255, 255));
        menuProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreria_ryr/pencil.png"))); // NOI18N
        menuProd.setText("Productos");
        menuProd.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N

        jMenuItem5.setText("Agregar Producto");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuProd.add(jMenuItem5);

        jMenuItem6.setText("Listar Productos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuProd.add(jMenuItem6);

        MenuAdm.add(menuProd);

        menuCat.setForeground(new java.awt.Color(255, 255, 255));
        menuCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreria_ryr/list-alt.png"))); // NOI18N
        menuCat.setText("Categorias");
        menuCat.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N

        jMenuItem7.setText("Agregar Categoria");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuCat.add(jMenuItem7);

        jMenuItem8.setText("Listar Categoria");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuCat.add(jMenuItem8);

        MenuAdm.add(menuCat);

        menuEmp.setForeground(new java.awt.Color(255, 255, 255));
        menuEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreria_ryr/address-card.png"))); // NOI18N
        menuEmp.setText("Empleados");
        menuEmp.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N

        jMenuItem9.setText("Agregar Empleado");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuEmp.add(jMenuItem9);

        jMenuItem10.setText("Listar Empleado");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menuEmp.add(jMenuItem10);

        MenuAdm.add(menuEmp);

        menuCliente.setForeground(new java.awt.Color(255, 255, 255));
        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreria_ryr/address-card-o.png"))); // NOI18N
        menuCliente.setText("Clientes");
        menuCliente.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N

        jMenuItem11.setText("Agregar Cliente");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menuCliente.add(jMenuItem11);

        jMenuItem12.setText("Listar Clientes");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        menuCliente.add(jMenuItem12);

        MenuAdm.add(menuCliente);

        setJMenuBar(MenuAdm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Agregar_proveedor aggOpen=new Agregar_proveedor();
        aggOpen.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Ingresar_productos aggProd=new Ingresar_productos();
        aggProd.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Agregar_categoria aggCat=new Agregar_categoria();
        aggCat.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Agregar_empleados aggEmp=new Agregar_empleados();
        aggEmp.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Datos_cliente aggCli= new Datos_cliente();
        aggCli.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        frmListar_cat lisCat= new frmListar_cat();
        lisCat.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        frmListar_prov lisProv=new frmListar_prov();
        lisProv.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        frmListar_emp lisEmp=new frmListar_emp();
        lisEmp.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        frmListar_cli lisClie=new frmListar_cli();
        lisClie.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       Nventa Gventa=new Nventa();
       Gventa.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuAdm;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu menuCat;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuEmp;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuProd;
    private javax.swing.JMenu menuProv;
    private javax.swing.JMenu menuVenta;
    // End of variables declaration//GEN-END:variables
}
