/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;

import conexion_db.ConexionDB;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel Benavides
 */
public class frmMostrarFac extends javax.swing.JFrame {

    /**
     * Creates new form MostrarFac
     */
    ConexionDB cn=new ConexionDB();
    public frmMostrarFac() {
        initComponents();
        this.setLocationRelativeTo(null);
        FactFiscal();   
    }
     public void FactFiscal(){
        
        ResultSet rs=cn.selectFactFiscal();
        DefaultTableModel model1=new DefaultTableModel();
         this.jTable2.setModel(model1);
        model1.setColumnIdentifiers(new Object[]{"ID FACTURA","CLIENTE","APELLIDO",
                "FECHA","ID VENTA","TIPO FACTURA","N° FACTURA","ESTADO_FACTURA"});
        

        try{
            while(rs.next()){
                model1.addRow(new Object[]{rs.getInt("ID_FACTURA"),rs.getString("NOMBRE_CLIE"),
                    rs.getString("APELLIDO_CLIE"),rs.getString("fecha_fact"),rs.getInt("id_venta"),
                    rs.getInt("tipo_fact"),rs.getInt("numero_fact"),
                    rs.getInt("estado_fact")});
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"No se encuentran datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtCambiar = new javax.swing.JButton();
        txtNFact = new javax.swing.JTextField();
        btnBuscarFact = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        txtCambiar.setText("Anular Factura");
        txtCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCambiarActionPerformed(evt);
            }
        });

        btnBuscarFact.setText("Buscar");
        btnBuscarFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNFact, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarFact)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCambiar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCambiar)
                    .addComponent(txtNFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarFact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCambiarActionPerformed
        // TODO add your handling code here:
        int idFac=0;
        int conf=0;
        int nfac=0;
        int filaseleccionada =  this.jTable2.getSelectedRow();
        if(filaseleccionada<0){
          JOptionPane.showMessageDialog(null, "Debe Selecionar una Factura");
         
        }else{
             idFac=Integer.parseInt(this.jTable2.getValueAt(filaseleccionada, 0).toString());
             nfac=Integer.parseInt(this.jTable2.getValueAt(filaseleccionada, 6).toString());
             conf=JOptionPane.showConfirmDialog(this, "Desea Anular la Factura: "+nfac,"Advertencia",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
             if(conf==JOptionPane.YES_OPTION){
                 cn.UpdateEstadoFact(String.valueOf(idFac));
                 FactFiscal(); 
             }else if(conf==JOptionPane.NO_OPTION){
                 FactFiscal();
             }
        }
        
    }//GEN-LAST:event_txtCambiarActionPerformed

    private void btnBuscarFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFactActionPerformed
        // TODO add your handling code here:
        if(this.txtNFact.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Campo Vacio");
        }else{
        String nfactura=this.txtNFact.getText().toString();
        ResultSet rs=cn.selectFactFiscal1(nfactura);
        DefaultTableModel model1=new DefaultTableModel();
         this.jTable2.setModel(model1);
        model1.setColumnIdentifiers(new Object[]{"ID FACTURA","CLIENTE","APELLIDO",
                "FECHA","ID VENTA","TIPO FACTURA","N° FACTURA","ESTADO_FACTURA"});
        

        try{
            while(rs.next()){
                model1.addRow(new Object[]{rs.getInt("ID_FACTURA"),rs.getString("NOMBRE_CLIE"),
                    rs.getString("APELLIDO_CLIE"),rs.getString("fecha_fact"),rs.getInt("id_venta"),
                    rs.getInt("tipo_fact"),rs.getInt("numero_fact"),
                    rs.getInt("estado_fact")});
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"No se encuentran datos");
            FactFiscal(); 
        }
        }
    }//GEN-LAST:event_btnBuscarFactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMostrarFac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMostrarFac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMostrarFac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMostrarFac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMostrarFac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFact;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton txtCambiar;
    private javax.swing.JTextField txtNFact;
    // End of variables declaration//GEN-END:variables
}
