/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ingreso_datos;

import entidades.Cliente;
import entidades.ClienteJpaController;
import entidades.entityMain;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marvin
 */
public class Datos_cliente extends javax.swing.JFrame {
    ClienteJpaController control_cliente = new ClienteJpaController(entityMain.getInstance());
    /**
     * Creates new form Datos_cliente
     */
    public Datos_cliente() {
        initComponents();
        CrearModelo2();
        LlenarTabla();
    }
    
   public static DefaultTableModel modelo2;
    private void CrearModelo2(){
        try {
            modelo2 = (new DefaultTableModel(
                null, new String [] {
                "id_cliente","Nombres",
                "apellido","direccion","NIT"
                ,"telefono","municipio","departamento",
                "N° Registro"}){
                Class[] types = new Class [] {
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,        
                java.lang.String.class,
                java.lang.String.class, 
                java.lang.String.class,
                };
                boolean[] canEdit = new boolean [] {
                false,false,false,false,false,false,false,false,false
                };
                @Override
                public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
                }
                @Override
                public boolean isCellEditable(int rowIndex, int colIndex){
                return canEdit [colIndex];
                }
            });
            this.jTable1.setModel(modelo2);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.toString()+"error2");
        }
    }
    
    private void LlenarTabla()
    {
        try{
            Object a[]=null;
            List<Cliente>ListaCliente;
            ListaCliente= control_cliente.findClienteEntities();
            for (int i = 0; i < ListaCliente.size(); i++) {
                modelo2.addRow(a);
                modelo2.setValueAt(ListaCliente.get(i).getIdCliente(),i, 0);
                modelo2.setValueAt(ListaCliente.get(i).getNombreClie(),i, 1);
                modelo2.setValueAt(ListaCliente.get(i).getApellidoClie(),i, 2);
                modelo2.setValueAt(ListaCliente.get(i).getDireccionClie(),i, 3);
                modelo2.setValueAt(ListaCliente.get(i).getNitClie(),i, 4);
                modelo2.setValueAt(ListaCliente.get(i).getTelefonoClie(),i, 5);
                modelo2.setValueAt(ListaCliente.get(i).getMunicipioClie(),i, 6);
                modelo2.setValueAt(ListaCliente.get(i).getDepartamentoClie(),i, 7);
                modelo2.setValueAt(ListaCliente.get(i).getNRegistroClie(),i, 8);               
            }
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNomClie = new javax.swing.JTextField();
        txtApellidoCli = new javax.swing.JTextField();
        txtDireccionClie = new javax.swing.JTextField();
        txtNitClie = new javax.swing.JTextField();
        txtTelefonoClie = new javax.swing.JTextField();
        txtMunucipioClie = new javax.swing.JTextField();
        txtDepartamentoClie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAggCliente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNregistroClie = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("NIT");

        jLabel6.setText("Telefono o celular");

        jLabel1.setText("Nombre del cliente");

        jLabel2.setText("Apellidos del cliente");

        jLabel3.setText("Direccion");

        jLabel7.setText("Municipio:");

        jLabel8.setText("Departamento:");

        txtNomClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomClieActionPerformed(evt);
            }
        });

        txtApellidoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCliActionPerformed(evt);
            }
        });

        txtDireccionClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionClieActionPerformed(evt);
            }
        });

        txtNitClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitClieActionPerformed(evt);
            }
        });

        txtTelefonoClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoClieActionPerformed(evt);
            }
        });

        txtMunucipioClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMunucipioClieActionPerformed(evt);
            }
        });

        txtDepartamentoClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartamentoClieActionPerformed(evt);
            }
        });

        jLabel4.setText("AGREGAR CLIENTES");

        btnAggCliente.setText("Guardar cliente");
        btnAggCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggClienteActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setText("Lista de clientes");

        jLabel10.setText("N° Registro:");

        txtNregistroClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNregistroClieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(297, 297, 297))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addComponent(jLabel6))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMunucipioClie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(txtTelefonoClie, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNitClie, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionClie, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoCli, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomClie, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDepartamentoClie)
                            .addComponent(txtNregistroClie))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(btnAggCliente)
                                .addGap(50, 50, 50)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNomClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtApellidoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDireccionClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNitClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTelefonoClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMunucipioClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtDepartamentoClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNregistroClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAggCliente)
                    .addComponent(jButton2))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomClieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomClieActionPerformed

    private void txtApellidoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCliActionPerformed

    private void txtDireccionClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionClieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionClieActionPerformed

    private void txtNitClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitClieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitClieActionPerformed

    private void txtTelefonoClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoClieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoClieActionPerformed

    private void txtMunucipioClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMunucipioClieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMunucipioClieActionPerformed

    private void txtDepartamentoClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartamentoClieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartamentoClieActionPerformed

    private void txtNregistroClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNregistroClieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNregistroClieActionPerformed

    private void btnAggClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggClienteActionPerformed
        String nombreClie=this.txtNomClie.getText();
        String apellidoClie=this.txtApellidoCli.getText();
        String  direccionClie=this.txtDireccionClie.getText();
        //int Nit=Integer.parseInt(this.txtNitClie.getText());
        String Nit=(this.txtNitClie.getText());
        String telefonoClie=this.txtTelefonoClie.getText();
        String municipioClie=this.txtMunucipioClie.getText();
        String departamentoClie=this.txtDepartamentoClie.getText();
        //int NRclie=Integer.parseInt(this.txtNregistroClie.getText());
        String NRclie=(this.txtNregistroClie.getText());
        
        ClienteJpaController t= new ClienteJpaController(entityMain.getInstance());
        Cliente cli= new Cliente();
        cli.setNombreClie(nombreClie);
        cli.setApellidoClie(apellidoClie);
        cli.setDireccionClie(direccionClie);
        cli.setNitClie((Nit));
        cli.setTelefonoClie(telefonoClie);
        cli.setMunicipioClie(municipioClie);
        cli.setDepartamentoClie(departamentoClie);
        cli.setNRegistroClie(NRclie);
        
        
        try
        {
            t.create(cli);
            JOptionPane.showMessageDialog(null,"Datos REgistrados");
            LlenarTabla();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }
        
    }//GEN-LAST:event_btnAggClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggCliente;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApellidoCli;
    private javax.swing.JTextField txtDepartamentoClie;
    private javax.swing.JTextField txtDireccionClie;
    private javax.swing.JTextField txtMunucipioClie;
    private javax.swing.JTextField txtNitClie;
    private javax.swing.JTextField txtNomClie;
    private javax.swing.JTextField txtNregistroClie;
    private javax.swing.JTextField txtTelefonoClie;
    // End of variables declaration//GEN-END:variables
}
